### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by MacsInSpace** [aquacash5/PodTube#1]
Receiving a 500 Error on testing. 
Any ideas?
`2019-08-27 12:38:47,791 500 GET /playlist/PL1bauNEiHIgwWzA2cOTeTW-nZeWsH7JPH (14.201.216.92) 314.01ms
2019-08-27 12:44:31,942 Playlist: PL1bauNEiHIgwWzA2cOTeTW-nZeWsH7JPH (14.201.216.92)
2019-08-27 12:44:32,309 Error Downloading Playlist: Bad Request
`

It seems to be ignoring the config file and only accepting command line options.
Is the YT API key mandatory? and if so, how is it added? Setting it via the command line looks like this:
`$ python podtube.py key AbcdefIzaSyDB6cStV5ATVRNEQRj_3Ev1234567 port 8181
usage: PodTube [-h] [--log-file FILE] [--log-format FORMAT] [-v] key [port]
PodTube: error: argument port: invalid int value: 'AbcdefIzaSyDB6cStV5ATVRNEQRj_3Ev1234567'`

**Comment by aquacash5** [comment]
Did you figure out the issue or give up?

**Comment by MacsInSpace** [comment]
Sort of both. :P  Podtube continued to ignore my config file.

To run it, I just used the command line as below.

`python podtube.py AbcdefIzaSyDB6cStV5ATVRNEQRj_3Ev1234567 8181`

**Comment by MacsInSpace** [comment]
Also, watch your folder permissions and dependencies.

**Comment by aquacash5** [comment]
Ya, there are no config files for Podtube. I just keep the "configuration" in a .sh file that I execute.

**Comment by aquacash5** [comment]
I see where it hints at one though

**Comment by MacsInSpace** [comment]
podtube.ini should be the config file but is ignored.

**Comment by aquacash5** [comment]
I forgot to delete that a while ago.

**Comment by MacsInSpace** [comment]
Ahh no problems. 
Thanks!
